name: 'nyc_trip_data'
version: '1.0.0'
profile: 'postgres_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_trip_data:
    +schema: dbt
    staging:
      +materialized: view
    core:
      +materialized: table
    mart:
      +materialized: table

vars:
  payment_type_values: [1, 2, 3, 4, 5, 6]
  is_test_run: true